version: '3.9'

services:
  # frontend vitejs + nginx
  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    working_dir: /www
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dist:/www
    depends_on:
      - flaskapp

  # backend
  flaskapp:
    image: python:3.11.6
    command: bash -c "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 80"
    working_dir: /api
    volumes:
      # - ./app.py:/app.py
      - ./api:/api
      - ./requirements.txt:/api/requirements.txt
    expose:
      - '80'

  #backend database
  mongodb:
    image: mongodb/mongodb-community-server:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
    expose:
      - '27017'
volumes:
  nginx-data:
  mongodb:
