FROM mydebianimage

RUN apt-get update && apt-get install -y gnupg2
RUN sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt bookworm-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
RUN apt-key adv --fetch-keys https://www.postgresql.org/media/keys/ACCC4CF8.asc

RUN apt-get update && apt-get -y install postgresql


EXPOSE 5432

CMD ["service", "postgresql", "start"]
