version: "3.9"

services:
  # dind service for internal Docker execution
  dind:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    networks:
      - jenkins
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports:
      - "2376:2376" # Expose Docker socket for internal use

  # Jenkins service using the internal Docker daemon
  jenkins:
    build: .
    restart: on-failure
    networks:
      - jenkins
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: "1"
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
      - jenkins-usr-local-go:/usr/local/go
    ports:
      - 8080:8080
      - 5000:5000

  # Golang build tools (unchanged)
  golang:
    image: golang:latest
    volumes:
      - jenkins-usr-local-go:/usr/local/go

volumes:
  jenkins-data:
  jenkins-docker-certs:
  jenkins-usr-local-go:

networks:
  jenkins:
