version: "1"

services:
  database:
    container_name: database_mysql_8
    image: mysql:8
    ports:
    - "3306:3306"
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--sort_buffer_size=512K",
        "--innodb_buffer_pool_size=1G",
        "--bulk_insert_buffer_size=256M",
        "--innodb_change_buffer_max_size=25",
        "--event_scheduler=on",
        "--sql_mode=NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,ONLY_FULL_GROUP_BY",
        "--max_allowed_packet=256M"
      ]
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=mydata
    - MYSQL_USER=ray
    - MYSQL_PASSWORD=ray
    networks:
    - cmnet

    volumes:
    - ./dump/dump.sql:/docker-entrypoint-initdb.d/00-init-db-schema.sql
    - ./dump/data.sql:/docker-entrypoint-initdb.d/00-init-test-data.sql

networks:
  cmnet:
    driver: bridge

